name: rad
channels:
  - anaconda
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.7.16
  - rdkit=2020.09.03
  - pip=22.3.1
  - numpy=1.21.5
  - tqdm=4.64.1
  - pybind11=2.10.1
  - graph-tool=2.29
  - jupyter=1.0.0
